### ISSUE TITLE
vscode (with godot tools) related issue - outline doesn't work - can class_name be added to limboAI demo files?

### ISSUE THREAD

**Issue by someThrowAway1900** [limbonaut/limboai#194] opened 2024-08-12 01:14 UTC
### Problem statement

**NOTE - This is not a limboAI specific issue.**

In vscode (with godot tools), it seems for outline to work, the first line should be 'extends' or else 'class_name' be added. Is it possible to include class_name as per the video?

https://github.com/user-attachments/assets/d66a2fa7-8679-463b-ab70-3544fbf29d49

### Proposed solution

suggest adding class_name to limboAI demo files.

### Alternatives

n/a - not sure

**Comment by limbonaut** [comment] 2024-08-26 10:40
This is an issue with godot-tools code extension. It's already reported upstream: https://github.com/godotengine/godot-vscode-plugin/issues/658

**Comment by limbonaut** [comment] 2024-11-15 19:29
PR: https://github.com/godotengine/godot/pull/99295

**Comment by limbonaut** [comment] 2024-12-17 22:50
The issue is fixed in the upstream, and should land with Godot 4.4 release.

**Closed by limbonaut** 2024-12-17 22:50 UTC
Labels: bug
