### ISSUE TITLE
GDExtension Editor Shortcuts Not Working

### ISSUE THREAD

**Issue by Atlinx** [limbonaut/limboai#86] opened 2024-04-07 00:23 UTC
I'm using Godot 4.2.1 with the LimboAI latest master branch commit (0ff93fa) GDExtension, and the editor shortcuts don't work. For example I can't use `delete` to delete a task, and I can't use `Ctrl + D` to duplicate a task.

**Comment by limbonaut** [comment] 2024-04-07 10:56
Strangely, it works as expected on my system with the latest build and GDExtension 4.2 branch. Which platform?
Anyone else experiencing this issue?

**Comment by Atlinx** [comment] 2024-04-07 15:25
I'm on Windows 11. Maybe the shortcuts are getting eaten by the scene hierarchy?

**Comment by masterthdev** [comment] 2024-04-07 18:48
In my setup shortcuts stop working only when this area is not focused:
![resim](https://github.com/limbonaut/limboai/assets/64798939/f30e180b-7841-44c1-ac8b-6167c36adc41)

Using input fields in the inspector(like custom_name) and using search bar in task list and clicking anything outside of LimboAI tab  removes focus from that area

**Comment by limbonaut** [comment] 2024-04-21 11:13
Still not sure how I can reproduce this. As masterthdev noted, the LimboAI editor accepts shortcuts only when it is focused. Which is reasonable, since you don't want LimboAI eat those shortcuts from the scene editor.

**Comment by limbonaut** [comment] 2024-05-29 10:01
This issue might be fixed in #122

**Comment by limbonaut** [comment] 2024-06-30 17:29
Closing this one, because issues that I found in shortcut processing I already fixed. Reopen if you still have this issue.

**Closed by limbonaut** 2024-06-30 17:29 UTC
Labels: bug

**Comment by adamfiserdev** [comment] 2025-06-22 14:29
Hello, I'm using 1.4.1 in Godot 4.4.1 and the keyboard shortcuts are not working. The shortcut will trigger action in the scene (ej. ctrl+D will duplicate selected node in scene instead of the task in BT).
